name: Feature Request
description: Open a feature request to Tidal-Media-Downloader.
title: "[FEATURE]: "
labels: feature request
body:
  - type: markdown
    attributes:
      value: |
        Please search for this issue in issues-page first. Avoid duplication.
        Please read Wiki first.
        https://github.com/yaronzz/Tidal-Media-Downloader/wiki
  - type: textarea
    id: which-tool
    attributes:
      label: Which tool
      description: Describe for which tool you want a feature to be added.
      placeholder: |
        tidal-gui or tidal-dl
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: Describe the feature as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Please add screenshots if available.
    validations:
      required: false
